In [6]:
!pip install pandas sklearn

Using legacy 'setup.py install' for sklearn, since package 'wheel' is not installed.
    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'


In [7]:
import pandas as pd

df = pd.read_csv('spotify_kaggle/data.csv')
df.head()

acousticness                                   artists  danceability  \
0         0.995                       ['Carl Woitschach']         0.708   
1         0.994  ['Robert Schumann', 'Vladimir Horowitz']         0.379   
2         0.604                   ['Seweryn Goszczyński']         0.749   
3         0.995                      ['Francisco Canaro']         0.781   
4         0.990  ['Frédéric Chopin', 'Vladimir Horowitz']         0.210   

   duration_ms  energy  explicit                      id  instrumentalness  \
0       158648  0.1950         0  6KbQ3uYMLKb5jDxLF7wYDD             0.563   
1       282133  0.0135         0  6KuQTIu1KoTTkLXKrwlLPV             0.901   
2       104300  0.2200         0  6L63VW0PibdM1HDSBoqnoM             0.000   
3       180760  0.1300         0  6M94FkXd15sOAOQYRnWPN8             0.887   
4       687733  0.2040         0  6N6tiFZ9vLTSOIxkj8qKrd             0.908   

   key  liveness  loudness  mode  \
0   10    0.1510   -12.428     1   
1    8    0.0763   -28.454     1   
2    5    0.1190   -19.924     0   
3    1    0.1110   -14.734     0   
4   11    0.0980   -16.829     1   

                                            name  popularity release_date  \
0                    Singende Bataillone 1. Teil           0         1928   
1       Fantasiestücke, Op. 111: Più tosto lento           0         1928   
2                 Chapter 1.18 - Zamek kaniowski           0         1928   
3  Bebamos Juntos - Instrumental (Remasterizado)           0   1928-09-25   
4    Polonaise-Fantaisie in A-Flat Major, Op. 61           1         1928   

   speechiness    tempo  valence  year  
0       0.0506  118.469   0.7790  1928  
1       0.0462   83.972   0.0767  1928  
2       0.9290  107.177   0.8800  1928  
3       0.0926  108.003   0.7200  1928  
4       0.0424   62.149   0.0693  1928

In [8]:
new_df = pd.read_csv('spotify2.csv')
new_df.head()

acousticness  artists  danceability  duration_ms  energy        id  \
0      0.998996  0.00000      0.716599     0.028442  0.1950  0.000000   
1      0.997992  0.00003      0.383603     0.051316  0.0135  0.000006   
2      0.606426  0.00006      0.758097     0.018374  0.2200  0.000012   
3      0.998996  0.00009      0.790486     0.032538  0.1300  0.000018   
4      0.993976  0.00012      0.212551     0.126450  0.2040  0.000024   

   instrumentalness       key  liveness  loudness  popularity  speechiness  \
0             0.563  0.909091    0.1510  0.745000        0.00     0.052219   
1             0.901  0.727273    0.0763  0.494026        0.00     0.047678   
2             0.000  0.454545    0.1190  0.627609        0.00     0.958720   
3             0.887  0.090909    0.1110  0.708887        0.00     0.095562   
4             0.908  1.000000    0.0980  0.676079        0.01     0.043756   

      tempo  valence      year  
0  0.485348   0.7790  0.070707  
1  0.344019   0.0767  0.070707  
2  0.439086   0.8800  0.070707  
3  0.442470   0.7200  0.070707  
4  0.254614   0.0693  0.070707

In [9]:
import pickle
filename = 'neighbors'

infile = open(filename,'rb')
model = pickle.load(infile)
infile.close()

In [10]:
def value_monad(a):
    return new_df.values.tolist()[a]

value_monad(1)

[0.997991967871486,
 2.9963444597590942e-05,
 0.3836032388663968,
 0.0513162067519365,
 0.0135,
 5.885538055889069e-06,
 0.901,
 0.7272727272727273,
 0.0763,
 0.4940255265836662,
 0.0,
 0.04767801857585138,
 0.3440192387265406,
 0.0767,
 0.07070707070707273]

In [11]:
def heigher_order_features(input_y):
    """A helper function for compare_this function, it creates
    a list with a specific row input"""
    state = []
    for i, x in enumerate(new_df.columns.tolist()):
        a = new_df[str(x)][input_y]
        state.append(a)
        
    return state

print(heigher_order_features(2))

[0.606425702811245, 5.9926889195181884e-05, 0.7580971659919029, 0.01837436036508649, 0.22, 1.1771076111778136e-05, 0.0, 0.4545454545454546, 0.119, 0.6276094276094277, 0.0, 0.9587203302373579, 0.4390862424259805, 0.88, 0.07070707070707273]


In [5]:
import plotly.graph_objects as go
import plotly.offline as pyo

def compare_this(a,b):

    categories = new_df.columns.tolist()

    fig = go.Figure()

    fig.add_trace(go.Scatterpolar(
        r=heigher_order_features(a),
        theta=categories,
        fill='toself',
        name='Product A'
    ))
    fig.add_trace(go.Scatterpolar(
        r=heigher_order_features(b),
        theta=categories,
        fill='toself',
        name='Product B'
    ))


    fig.update_layout(
    polar=dict(
      radialaxis=dict(
        visible=True,
        range=[0, 1]
      )),
    showlegend=False
    )
    
    pyo.iplot(fig, filename = 'basic-line')

compare_this(100,200)

NameError: name 'new_df' is not defined

In [13]:
print(model.kneighbors([value_monad(10000)]))

(array([[0.        , 0.26437765, 0.26623907, 0.28723417, 0.30341281,
        0.31390304, 0.32246313, 0.32313638, 0.32415728, 0.32679204,
        0.32883792, 0.33545995, 0.33711348, 0.33724571, 0.34088624,
        0.34282455, 0.34399587, 0.34404901, 0.34761091, 0.3498265 ]]), array([[10000, 18201,  2611, 35170, 26469, 26655, 18360,  8941, 49579,
         3038, 11263, 11720, 11185, 19080, 26064, 18835,  1449, 19030,
        10249, 19130]], dtype=int64))


In [14]:
def search_id_monad(a):
    b = model.kneighbors([value_monad(a)])
    return b[1]

In [16]:
search_id_monad(10000)

array([[10000, 18201,  2611, 35170, 26469, 26655, 18360,  8941, 49579,
         3038, 11263, 11720, 11185, 19080, 26064, 18835,  1449, 19030,
        10249, 19130]], dtype=int64)

In [17]:
df.values[10000]

array([0.488, "['Martin Denny']", 0.301, 186000, 0.249, 0,
       '6UMAEsJEaKEN7Y2GXtid5a', 0.0012, 1, 0.11199999999999999, -16.408,
       1, 'Forbidden Island', 10, '1958-01-01', 0.0315, 89.51799999999999,
       0.0494, 1958], dtype=object)

In [18]:
def run_model(a):
    monad = search_id_monad(a)
    data = [monad[0][0], monad[0][1]]
    meta_data = [
        df.values.tolist()[data[0]],
        df.values.tolist()[data[1]]]
    return [compare_this(data[0], data[1]), meta_data]
    
run_model(10000)

[None,
 [[0.488,
   "['Martin Denny']",
   0.301,
   186000,
   0.249,
   0,
   '6UMAEsJEaKEN7Y2GXtid5a',
   0.0012,
   1,
   0.11199999999999999,
   -16.408,
   1,
   'Forbidden Island',
   10,
   '1958-01-01',
   0.0315,
   89.51799999999999,
   0.0494,
   1958],
  [0.54,
   "['Eddie Cochran']",
   0.33,
   139533,
   0.185,
   0,
   '2Bpf44xO9EcGEVewLuOLmN',
   0.0288,
   2,
   0.122,
   -14.31,
   1,
   'Tell Me Why',
   17,
   '1960-05-01',
   0.0343,
   140.356,
   0.0795,
   1960]]]

In [19]:
compare_this(10000, 18201)

In [23]:
search_id_monad(10000)[0]

array([10000, 18201,  2611, 35170, 26469, 26655, 18360,  8941, 49579,
        3038, 11263, 11720, 11185, 19080, 26064, 18835,  1449, 19030,
       10249, 19130], dtype=int64)

## Quantum Phonic playlist

Postprocessing playlists based off of strawberryfields, a python library for high-level functions for near term phonic devices. 

In [31]:
def degrees_sep(song_id_in): 
    
    state = []
    for i,x in enumerate(search_id_monad(song_id_in)[0]):
        state.append((search_id_monad(song_id_in)[0][0], x))

    return state

print(degrees_sep(10000))

[(10000, 10000), (10000, 18201), (10000, 2611), (10000, 35170), (10000, 26469), (10000, 26655), (10000, 18360), (10000, 8941), (10000, 49579), (10000, 3038), (10000, 11263), (10000, 11720), (10000, 11185), (10000, 19080), (10000, 26064), (10000, 18835), (10000, 1449), (10000, 19030), (10000, 10249), (10000, 19130)]


In [49]:
def multi_degrees_sep(song_id_in, level): 
    
    state = []
    for i,x in enumerate(search_id_monad(song_id_in)[0]):
        state.append((search_id_monad(song_id_in)[0][0], x))
        
    state2 = []
    
    state3 = []
    for i,y in enumerate(state):
        try:
            # takes current state
            current = state[i][1]
            # prints out state
            print(state[i][1])
            # appends state
            state2.append(state[i][1])
            # finds relationships
            #ndegree = degrees_sep(song_id_in)
            
        except:
            continue
    
    return {'First Degree': state,
            'placeholder': state2}

multi_degrees_sep(10000,1)

10000
18201
2611
35170
26469
26655
18360
8941
49579
3038
11263
11720
11185
19080
26064
18835
1449
19030
10249
19130


{'First Degree': [(10000, 10000),
  (10000, 18201),
  (10000, 2611),
  (10000, 35170),
  (10000, 26469),
  (10000, 26655),
  (10000, 18360),
  (10000, 8941),
  (10000, 49579),
  (10000, 3038),
  (10000, 11263),
  (10000, 11720),
  (10000, 11185),
  (10000, 19080),
  (10000, 26064),
  (10000, 18835),
  (10000, 1449),
  (10000, 19030),
  (10000, 10249),
  (10000, 19130)],
 'placeholder': [10000,
  18201,
  2611,
  35170,
  26469,
  26655,
  18360,
  8941,
  49579,
  3038,
  11263,
  11720,
  11185,
  19080,
  26064,
  18835,
  1449,
  19030,
  10249,
  19130]}

state = [('a','b'),
         ('c','d')]

state[0][1]

In [33]:
from strawberryfields.apps import data, plot, sample, clique
import numpy as np
import networkx as nx
import plotly

def visualize_deg_sep(song_id_in):
    G = nx.Graph()
    G.add_nodes_from(search_id_monad(song_id_in)[0])
    G.add_edges_from(degrees_sep(song_id_in))
    
    maximal_clique = search_id_monad(song_id_in)[0]

    
    return plot.graph(G, 
               maximal_clique, 
               subgraph_node_colour='#1DB954',
               subgraph_edge_colour='#1DB954',
               graph_node_colour='#ffffff',
               graph_edge_colour='#ffffff',
               background_color='#191414',
               graph_node_size=5)

visualize_deg_sep(10000)



ImportError: attempted relative import with no known parent package